-- DDL for Table BOARD

CREATE TABLE BOARD (
  BOARD_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NUM)
);

-- DDL for Table BOARD_REPLY

CREATE TABLE BOARD_REPLY (
  RE_NUM NUMBER NOT NULL,
  BOARD_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_BOARD_REPLY PRIMARY KEY (RE_NUM)
);

-- DDL for Table BOOKING

CREATE TABLE BOOKING (
  BK_NUM NUMBER NOT NULL,
  ROOM_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  BOOK_MEM VARCHAR2(255) NOT NULL,
  BK_STATUS VARCHAR2(255) NOT NULL,
  BK_DATE DATE NOT NULL,
  START_TIME DATE NOT NULL,
  END_TIME DATE NOT NULL,
  CONSTRAINT PK_BOOKING PRIMARY KEY (BK_NUM)
);

-- DDL for Table FIX

CREATE TABLE FIX (
  FIX_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  MEM_AUTH VARCHAR2(255) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_FIX PRIMARY KEY (FIX_NUM)
);

-- DDL for Table FIX_REPLY

CREATE TABLE FIX_REPLY (
  RE_NUM NUMBER NOT NULL,
  FIX_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_FIX_REPLY PRIMARY KEY (RE_NUM)
);

-- DDL for Table INQUIRY

CREATE TABLE INQUIRY (
  IN_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_INQUIRY PRIMARY KEY (IN_NUM)
);

-- DDL for Table INQUIRY_MANAGE

CREATE TABLE INQUIRY_MANAGE (
  RE_NUM NUMBER NOT NULL,
  IN_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_INQUIRY_MANAGE PRIMARY KEY (RE_NUM)
);

-- DDL for Table MEMBER

CREATE TABLE MEMBER (
  MEM_NUM NUMBER NOT NULL,
  DONGHO VARCHAR2(255) NOT NULL,
  AUTH VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_MEMBER PRIMARY KEY (MEM_NUM)
);

-- DDL for Table MEMBER_DETAIL

CREATE TABLE MEMBER_DETAIL (
  MEM_NUM NUMBER NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  PASSWD VARCHAR2(255) NOT NULL,
  PHONE VARCHAR2(255) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  CONSTRAINT PK_MEMBER_DETAIL PRIMARY KEY (MEM_NUM)
);

-- DDL for Table NOTICE

CREATE TABLE NOTICE (
  NO_NUM NUMBER NOT NULL,
  DEPT VARCHAR2(255) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CATEGORY_STATUS VARCHAR2(255) NOT NULL,
  STATUS VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_NOTICE PRIMARY KEY (NO_NUM)
);

-- DDL for Table QUESTION

CREATE TABLE QUESTION (
  QUE_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_QUESTION PRIMARY KEY (QUE_NUM)
);

-- DDL for Table ROOM_INFO

CREATE TABLE ROOM_INFO (
  ROOM_NUM NUMBER NOT NULL,
  ROOM_TYPE VARCHAR2(255) NOT NULL,
  ROOM_NAME VARCHAR2(255) NOT NULL,
  ROOM_STATUS VARCHAR2(255) NOT NULL,
  TOTAL_MEM VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_ROOM_INFO PRIMARY KEY (ROOM_NUM)
);

-- DDL for Table SECONDHAND

CREATE TABLE SECONDHAND (
  SE_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  DIVISION VARCHAR2(255) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_SECONDHAND PRIMARY KEY (SE_NUM)
);

-- DDL for Table SECONDHAND_FAV

CREATE TABLE SECONDHAND_FAV (
  FAV_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  SE_NUM NUMBER NOT NULL,
  CONSTRAINT PK_SECONDHAND_FAV PRIMARY KEY (FAV_NUM)
);

-- DDL for Table SECONDHAND_REPLY

CREATE TABLE SECONDHAND_REPLY (
  RE_NUM NUMBER NOT NULL,
  MEM_NUM NUMBER NOT NULL,
  SE_NUM NUMBER NOT NULL,
  CONTENT VARCHAR2(255) NOT NULL,
  REG_DATE DATE NOT NULL,
  IP VARCHAR2(255) NOT NULL,
  CONSTRAINT PK_SECONDHAND_REPLY PRIMARY KEY (RE_NUM),
  CONSTRAINT FK_SECONDHAND_TO_SECONDHAND_REPLY_1 FOREIGN KEY (SE_NUM) REFERENCES SECONDHAND (SE_NUM),
  CONSTRAINT FK_SECONDHAND_REPLY_MEMBER_NUM FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM)
);
